name: Publish
description: Publishes the project.

inputs:
  nuget_api_key:
    description: "NuGet API key used to publish the package to NuGet.org"
    required: true
  github_token:
    description: "GitHub token used to create git tags"
    required: true
  tags:
    description: "Currently existing git tags"
    required: true
  versions:
    description: "Versions of the projects"
    required: true

runs:
  using: node24
  main: dist/index.js
